"""
Pydantic models for the SHL Assessment Recommender API.

CRITICAL: The response schema is non-negotiable. Deviating breaks the automated
evaluator. These models are the single source of truth.

Design note: We keep the API models separate from internal data models.
The API models match the assignment spec exactly. Internal models (Assessment, Slots)
are richer and used only within the application.
"""

from __future__ import annotations

from pydantic import BaseModel, Field
from typing import Optional


# ============================================================================
# API Models — match assignment spec EXACTLY
# ============================================================================

class Message(BaseModel):
    """A single message in the conversation history."""
    role: str = Field(..., description="Either 'user' or 'assistant'")
    content: str = Field(..., description="The message text")


class ChatRequest(BaseModel):
    """
    POST /chat request body.
    
    The API is stateless: every call carries the full conversation history.
    No per-conversation state is stored server-side.
    """
    messages: list[Message]


class Recommendation(BaseModel):
    """
    A single assessment recommendation.
    
    name and url MUST come from the SHL catalog — never generated by the LLM.
    test_type is inferred from the assessment's category keys.
    """
    name: str = Field(..., description="Assessment name from catalog")
    url: str = Field(..., description="Catalog URL — must be a real SHL URL")
    test_type: str = Field(..., description="Test type code(s): K, P, A, B, S, C, D")


class ChatResponse(BaseModel):
    """
    POST /chat response body.
    
    Rules from the assignment:
    - recommendations is EMPTY LIST when agent is gathering context or refusing
    - recommendations is 1-10 items when agent has committed to a shortlist
    - end_of_conversation is true ONLY when agent considers task complete
    """
    reply: str = Field(..., description="Agent's natural language response")
    recommendations: list[Recommendation] = Field(
        default_factory=list,
        description="Empty when clarifying/refusing, 1-10 items when recommending"
    )
    end_of_conversation: bool = Field(
        default=False,
        description="True only when the agent considers the conversation complete"
    )


# ============================================================================
# Internal Models — richer representations for application logic
# ============================================================================

class Assessment(BaseModel):
    """
    Internal representation of a single SHL catalog assessment.
    Normalized from the raw JSON catalog.
    """
    entity_id: str
    name: str
    url: str                           # renamed from 'link'
    job_levels: list[str] = Field(default_factory=list)
    languages: list[str] = Field(default_factory=list)
    duration_minutes: Optional[int] = None   # parsed from e.g. "30 minutes"
    duration_raw: str = ""
    remote: bool = True
    adaptive: bool = False
    description: str = ""
    categories: list[str] = Field(default_factory=list)  # renamed from 'keys'
    test_type_code: str = ""           # Inferred: K, P, A, B, etc.
    search_text: str = ""              # Concatenated text for TF-IDF indexing
    name_lower: str = ""               # Precomputed lowercase name for fuzzy matching

    def to_recommendation(self) -> Recommendation:
        """Convert to API recommendation format."""
        return Recommendation(
            name=self.name,
            url=self.url,
            test_type=self.test_type_code,
        )


class ConversationSlots(BaseModel):
    """
    Structured slots extracted from conversation history by the LLM.
    
    These drive retrieval queries and decision-making in the controller.
    Designed to capture everything the sample conversations demonstrate.
    """
    role: Optional[str] = ""            # "Java developer", "contact centre agent"
    skills: list[str] = Field(default_factory=list)  # ["Java", "Spring", "SQL"]
    seniority: Optional[str] = ""       # "entry-level", "graduate", "manager", "executive"
    job_level: str = ""                 # Maps to catalog's job_levels field
    language: str = ""                  # Required language for assessments
    test_types_wanted: list[str] = Field(default_factory=list)  # ["knowledge", "personality", "cognitive"]
    industry: str = ""                  # "manufacturing", "healthcare"
    purpose: str = ""                   # "selection", "development", "audit"
    specific_assessments: list[str] = Field(default_factory=list)  # Named assessments
    additions: list[str] = Field(default_factory=list)    # Things to add
    removals: list[str] = Field(default_factory=list)     # Things to remove
    other_context: str = ""             # Free-form additional context
    has_enough_info: bool = False       # LLM's judgment on whether to recommend
    volume: str = ""                    # "high-volume" screening vs individual
    jd_text: str = ""                   # If user pasted a job description
